steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/patient-db/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: 'maven:3-jdk-8'
    id: 'Build all hmftools'
    entrypoint: mvn
    args: [ 'clean', 'install', '-B' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - name: 'maven:3-jdk-8'
    id: 'Setting version'
    dir: patient-db
    entrypoint: mvn
    args: ['versions:set', '-DnewVersion=3.62.${_PATCH_VERSION}']
  - name: 'maven:3-jdk-8'
    id: 'Generate and deploy patient db jar'
    dir: patient-db
    entrypoint: mvn
    args: ['clean', 'deploy', '-B', '-P', 'shade']
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/hmfapi-java-client/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
